---

- name: Ensure listed dirs exist
  file:
    path: '{{ item }}'
    state: directory
  loop: "{{ list_dir_ensure }}"

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: docker systemd
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Allow nginx firewall
  ufw: proto=tcp port=80 rule=allow
- name: Allow nginx ssl firewall
  ufw: proto=tcp port=443 rule=allow